### ISSUE TITLE
[Help] Conflict with MUI in Storybook

### ISSUE THREAD

**Issue by marc-gavanier** [codegouvfr/react-dsfr#14]
Standard preview of badge component shows like this:
![image](https://user-images.githubusercontent.com/68475403/206033280-05ddb4e6-504c-4230-9b72-11bd99a1a081.png)

But when I apply `isSmall` property

![image](https://user-images.githubusercontent.com/68475403/206033512-83252ca5-603a-43d8-8b80-857f86d436ba.png)

The preview renders with a text size issue:

![image](https://user-images.githubusercontent.com/68475403/206033764-fefd4bb5-77ab-4ae0-8531-1ea1372fe7aa.png)

After looking in navigator inspector, I noticed that `.fr-badge--sm` has been overriden
```css
fr-badge--sm {
  font-size: 0.75rem; /* overriden */
  line-height: 1.25rem; /* overriden */
  min-height: 1.125rem;
  padding: 0 0.375rem;
  overflow: initial;
  max-width: 100%;
  max-height: none;
}
```
It appears that `p:not([class^="Mui"])` is responsible of this behaviour:
```css
p:not([class^="Mui"]) {
  font-size: 1rem;
  line-height: 1.5rem;
  margin: var(--text-spacing);
}
```
Preview is OK after disabling `font-size` and `line-height` styles:
![image](https://user-images.githubusercontent.com/68475403/206035537-03065211-21b2-4ddd-a767-3ead4a3c8c35.png)

After looking in project files, `p:not([class^="Mui"])` selector is present in `dsfr/dsfr(.min).css` files which are generated while running `yarn build` command.

This code in `patchCssForMui.ts` is probably the root of the problem:
```typescript
const selectorNotMui = `${selector}:not([class^="Mui"])`;

if (media === "root") {
    if (selector === "[href]") {
        return selectorNotMui;
    }

    if (selector === "p") {
        return selectorNotMui;
    }
}
```
